FROM mottosso/maya:2016sp1

RUN wget https://bootstrap.pypa.io/get-pip.py && \
	mayapy get-pip.py && \
	mayapy -m pip install \
		nose \
		nose-exclude \
		coverage \
		pyblish-base==1.4.2 \
		pyblish-maya \
		pymongo \
		python-coveralls

# Avoid creation of auxilliary files
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /workspace

ENTRYPOINT \
	mayapy -u run_maya_tests.py && \
	mayapy -c "from coveralls import wear;wear()"
