FROM mottosso/maya:2016sp1

RUN wget https://bootstrap.pypa.io/get-pip.py && \
	mayapy get-pip.py && \
	mayapy -m pip install \
		nose \
		nose-exclude \
		pyblish-base==1.4.2 \
		pyblish-maya \
		pymongo \
		sphinx \
		six \
		sphinxcontrib-napoleon \
		coveralls

# Avoid creation of auxilliary files
ENV PYTHONDONTWRITEBYTECODE=1
ENV TRAVIS=1

WORKDIR /workspace

ENTRYPOINT \
	PYTHONPATH=$(pwd):$PYTHONPATH mayapy -u run_maya_tests.py && \
	mayapy -m coveralls
